# Generated by Django 5.1.4 on 2024-12-21 21:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('equipment', '0003_alter_equipment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id_assignment', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('id_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Asignación',
                'ordering': ['-assignment_date'],
            },
        ),
    ]
