# Generated by Django 5.1.4 on 2024-12-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id_equipment', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type_equipment', models.CharField(choices=[('TIPO1', 'tipo1'), ('TIPO2', 'tipo2')], max_length=10, verbose_name='Tipo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('serial_number', models.IntegerField(unique=True, verbose_name='Número de serie')),
                ('status', models.CharField(max_length=100, verbose_name='Estatus')),
                ('location', models.CharField(max_length=100, verbose_name='Locación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
        ),
    ]
