# Generated by Django 5.1.4 on 2024-12-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['-created'], 'verbose_name': 'Equipos'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type_equipment',
            field=models.CharField(choices=[('TIPO1', 'Tipo1'), ('TIPO2', 'Tipo2')], max_length=10, verbose_name='Tipo'),
        ),
    ]
